ln -s ~/.dot_configs/.bashrc ~/.bashrc
ln -s ~/.dot_configs/.gitconfig ~/.gitconfig
ln -s ~/.dot_configs/.gitignore_global ~/.gitignore_global
ln -s ~/.dot_configs/.offlineimaprc ~/.offlineimaprc
ln -s ~/.dot_configs/.pryrc ~/.pryrc
ln -s ~/.dot_configs/.pythonrc .pythonrc
ln -s ~/.dot_configs/.tmux.conf ~/.tmux.conf
ln -s ~/.dot_configs/.vim ~/.vim
ln -s ~/.dot_configs/.vim/.vimrc ~/.vimrc
ln -s ~/.dot_configs/.zshrc ~/.zshrc
ln -s ~/.dot_configs/.rspec ~/.rspec
